apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{cookiecutter.project_slug}}-production
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-persistent-volume-claim
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-persistent-volume-claim
      containers:
        - name: backend
          image: registry.gitlab.com/{{cookiecutter.gitlab_group_name}}/{{cookiecutter.project_dirname}}:__IMAGE_TAG__
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: static-storage
              mountPath: /app/static
              subPath: static
            - name: media-storage
              mountPath: /app/media
              subPath: media
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-cluster-ip-service:5432/$(POSTGRES_DB)
            - name: DJANGO_CONFIGURATION
              valueFrom:
                secretKeyRef:
                  name: development-{{cookiecutter.project_slug}}-secrets
                  key: DJANGO_CONFIGURATION
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_ALLOWED_HOSTS
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_SECRET_KEY
            - name: DJANGO_SERVER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_SERVER_EMAIL
            - name: DJANGO_DEBUG
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_DEBUG
            - name: EMAIL_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: EMAIL_URL

---

apiVersion: v1
kind: Service
metadata:
  name: backend-cluster-ip-service
  namespace: {{cookiecutter.project_slug}}-production
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
