"""Web project initialization CLI constants."""

GITLAB_TOKEN_ENV_VAR = "GITLAB_PRIVATE_TOKEN"

MEDIA_STORAGE_CHOICES = ["local", "s3-digitalocean", "none"]

MEDIA_STORAGE_DEFAULT = "s3-digitalocean"

TERRAFORM_BACKEND_DEFAULT = "gitlab"

TERRAFORM_BACKEND_TFC = "terraform-cloud"

TERRAFORM_BACKEND_CHOICES = [TERRAFORM_BACKEND_DEFAULT, TERRAFORM_BACKEND_TFC]
