[tool.black]
target-version = ["py310"]

[tool.isort]
atomic = true
combine_as_imports = true
default_section = "THIRDPARTY"
known_local_folder = [
    "pacts",
]
known_third_party = [
    "django",
]
profile = "black"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
