[tool.black]
target-version = ["py312"]

[tool.coverage.html]
title = "Django Continuous Delivery - Coverage"

[tool.coverage.report]
fail_under = 79
show_missing = true

[tool.coverage.run]
branch = true
dynamic_context = "test_function"
omit = [
    ".venv/*",
    "venv/*",
]
source = ["."]

[tool.mypy]
enable_error_code = [
    "truthy-bool",
]
ignore_missing_imports = true
python_version = "3.12"

[tool.bandit]
exclude_dirs = [
    ".venv",
    "tests",
    "features"
]

[tool.ruff]
extend-exclude = [
    "__pycache__",
    ".vscode*",
]
ignore = [
    "D203",
    "D212",
    "D213",
    "D214",
    "D215",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D413",
    "D415",
    "D416",
    "D417",
]
select = [
    "B",
    "C",
    "D",
    "E",
    "F",
    "I",
    "W",
    "B9"
]
target-version = "py312"

[tool.ruff.isort]
known-first-party = [
    "bootstrap",
]
