stages:
  - Test
  - Pact-verify
  - Pact-check
  - Build
  - Deploy
  - Pact-tag
  - Report
  - Sentry

variables:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  PACT_PROVIDER_NAME: {{ cookiecutter.project_slug }}-{{ cookiecutter.service_slug }}
  PROJECT_SLUG: {{ cookiecutter.project_slug }}
  SENTRY_PROJECT_NAME: {{ cookiecutter.project_slug }}-{{ cookiecutter.service_slug }}
  VERSION_BEFORE_REF: ${CI_COMMIT_BEFORE_SHA}
  VERSION_REF: ${CI_COMMIT_SHA}
{% with env=cookiecutter.resources.envs[0] %}
.development:
  rules: &development-rules
    - &pipeline-push-rule
      if: $CI_PIPELINE_SOURCE != "push"
      when: never
    - &development-rule
      if: $CI_COMMIT_BRANCH == "develop"
      variables:
        ENV_SLUG: {{ env.slug }}
        STACK_SLUG: {{ env.stack_slug }}
        VAULT_ROLE: {{ cookiecutter.service_slug }}-{{ env.slug }}
  environment:
    name: {{ env.name }}{% if env.url %}
    url: {{ env.url }}{% endif %}
{% endwith %}{% with env=cookiecutter.resources.envs[1] %}
.staging:
  rules: &staging-rules
    - <<: *pipeline-push-rule
    - &staging-rule
      if: $CI_COMMIT_BRANCH == "main"
      variables:
        ENV_SLUG: {{ env.slug }}
        STACK_SLUG: {{ env.stack_slug }}
        VAULT_ROLE: {{ cookiecutter.service_slug }}-{{ env.slug }}
  environment:
    name: {{ env.name }}{% if env.url %}
    url: {{ env.url }}{% endif %}
{% endwith %}{% with env=cookiecutter.resources.envs[2] %}
.production:
  rules: &production-rules
    - <<: *pipeline-push-rule
    - &production-rule
      if: $CI_COMMIT_TAG
      variables:
        ENV_SLUG: {{ env.slug }}
        STACK_SLUG: {{ env.stack_slug }}
        VAULT_ROLE: {{ cookiecutter.service_slug }}-{{ env.slug }}
  environment:
    name: {{ env.name }}{% if env.url %}
    url: {{ env.url }}{% endif %}
{% endwith %}
.sentry:
  stage: .pre
  image: docker:20
  services:
    - docker:20-dind{% if cookiecutter.use_vault == "true" %}
  id_tokens:
    VAULT_ID_TOKEN:
      aud: ${VAULT_ADDR}{% endif %}
  script:
    - >
      docker run --rm
      -v ${PWD}:${PWD}
      -w ${PWD}
      -e CI_ENVIRONMENT_NAME{% if cookiecutter.use_vault == "true" %}
      -e ENV_NAME=${CI_ENVIRONMENT_NAME}{% endif %}
      -e PROJECT_DIR=${CI_PROJECT_DIR}
      -e PROJECT_SLUG
      -e RELEASE_END
      -e RELEASE_START{% if cookiecutter.use_vault == "false" %}
      -e SENTRY_AUTH_TOKEN
      -e SENTRY_DSN{% endif %}
      -e SENTRY_ORG
      -e SENTRY_PROJECT_NAME
      -e SENTRY_URL{% if cookiecutter.use_vault == "true" %}
      -e SERVICE_SLUG={{ cookiecutter.service_slug }}
      -e VAULT_ADDR
      -e VAULT_ID_TOKEN
      -e VAULT_ROLE{% endif %}
      -e VERSION_REF
      --entrypoint=""
      getsentry/sentry-cli:latest ./scripts/ci_sentry.sh ${SENTRY_CMD}

.sentry_release:
  extends:
    - .sentry
  variables:
    SENTRY_CMD: release
  before_script:
    - RELEASE_START=$(date +%s)

sentry_release_development:
  extends:
    - .development
    - .sentry_release
  rules:
    - &sentry-rule
      if: $SENTRY_ENABLED != "true"
      when: never
    - *development-rules

sentry_release_staging:
  extends:
    - .staging
    - .sentry_release
  rules:
    - <<: *sentry-rule
    - *staging-rules

sentry_release_production:
  extends:
    - .production
    - .sentry_release
  rules:
    - <<: *sentry-rule
    - *production-rules

test:
  stage: Test
  image: docker:20
  services:
    - docker:20-dind
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  variables:
    {{ cookiecutter.service_slug|upper }}_CONTAINER_NAME: "${CI_PROJECT_PATH_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}_{{ cookiecutter.service_slug }}"
    {{ cookiecutter.service_slug|upper }}_BUILD_TARGET: "test"
    {{ cookiecutter.service_slug|upper }}_IMAGE_NAME: "gitlabci_{{ cookiecutter.project_slug }}_{{ cookiecutter.service_slug }}"
    {{ cookiecutter.service_slug|upper }}_IMAGE_TAG: "${CI_JOB_NAME}-${CI_JOB_ID}"
    COMPOSE_PROJECT_NAME: "${CI_PROJECT_PATH_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}"
  script:
    - docker-compose build
    - docker-compose run --name ${{ "{" }}{{ cookiecutter.service_slug|upper }}_CONTAINER_NAME} {{ cookiecutter.service_slug }}
    - docker cp ${{ "{" }}{{ cookiecutter.service_slug|upper }}_CONTAINER_NAME}:/app/htmlcov htmlcov
  after_script:
    - docker-compose down -v
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    expire_in: 1 day
    paths:
      - htmlcov
    when: always

pact-verify-test:
  stage: Pact-verify
  image: docker:20
  services:
    - docker:20-dind{% if cookiecutter.use_vault == "true" %}
  id_tokens:
    VAULT_ID_TOKEN:
      aud: ${VAULT_ADDR}{% endif %}
  needs: []
  variables:
    {{ cookiecutter.service_slug|upper }}_BUILD_TARGET: "test"
    {{ cookiecutter.service_slug|upper }}_IMAGE_NAME: "gitlabci_{{ cookiecutter.project_slug }}_{{ cookiecutter.service_slug }}"
    {{ cookiecutter.service_slug|upper }}_IMAGE_TAG: "${CI_JOB_NAME}-${CI_JOB_ID}"
    COMPOSE_PROJECT_NAME: "${CI_PROJECT_PATH_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}"
  rules:
    - <<: *pipeline-push-rule
    - if: $PACT_ENABLED == "true"
      allow_failure: true
  before_script: &pact-verify-before-script{% if cookiecutter.use_vault == "true" %}
    - >
      vault_token=$(wget --quiet --post-data="role=pact&jwt=${VAULT_ID_TOKEN}"
      "${VAULT_ADDR%/}"/v1/auth/gitlab-jwt/login -O - |
      sed -n 's/^.*"client_token":"\([^"]*\)".*$/\1/p')
    - >
      PACT_BROKER_AUTH_URL=$(wget --quiet --header="X-Vault-Token: ${vault_token}"
      "${VAULT_ADDR%/}"/v1/"${PROJECT_SLUG}"/pact -O - |
      sed -n 's/^.*"pact_broker_auth_url":"\([^"]*\)".*$/\1/p'){% endif %}
    - export PACT_BROKER_URL="${PACT_BROKER_AUTH_URL}"
  script:
    - >
      if [ "${CI_COMMIT_BRANCH}" ];
      then PACT_CONSUMER_TAG="branch:${CI_COMMIT_BRANCH}";
      else PACT_CONSUMER_TAG="tag:${CI_COMMIT_TAG}";
      fi
    - docker-compose build
    - >
      docker-compose run --rm {{ cookiecutter.service_slug }} ./scripts/pact_verify.sh
      --pact-provider-version=${VERSION_REF}
      --pact-verify-consumer-tag=${PACT_CONSUMER_TAG}
      --pact-verify-consumer-tag="env:dev"
      --pact-verify-consumer-tag="env:stage"
      --pact-verify-consumer-tag="env:prod"
      --pact-publish-results
  after_script:
    - docker-compose down -v

pact-verify-webhook:
  stage: Pact-verify
  image: docker:20
  services:
    - docker:20-dind
  variables:
    COMPOSE_PROJECT_NAME: "${CI_PROJECT_PATH_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}"
    {{ cookiecutter.service_slug|upper }}_IMAGE_NAME: "gitlabci_{{ cookiecutter.project_slug }}_{{ cookiecutter.service_slug }}"
    {{ cookiecutter.service_slug|upper }}_BUILD_TARGET: "test"
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger" && $PACT_ENABLED == "true"
      allow_failure: true
  before_script: *pact-verify-before-script
  script:
    - docker-compose build
    - >
      docker-compose run --rm {{ cookiecutter.service_slug }} ./scripts/pact_verify.sh
      --pact-provider-version=${VERSION_REF}
      --pact-verify-consumer-tag=${PACT_CONSUMER_TAG}
      --pact-publish-results
  after_script:
    - docker-compose down -v

pages:
  stage: Report
  image: busybox
  needs: ["test"]
  rules:
    - <<: *pipeline-push-rule
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mkdir public
    - mv htmlcov public/htmlcov
  artifacts:
    paths:
      - public

.pact:
  image:
    name: docker:20
  services:
    - docker:20-dind{% if cookiecutter.use_vault == "true" %}
  id_tokens:
    VAULT_ID_TOKEN:
      aud: ${VAULT_ADDR}{% endif %}
  script:
    - >
      docker run --rm
      -v ${PWD}:${PWD}
      -w ${PWD}{% if cookiecutter.use_vault == "true" %}
      -e ENV_SLUG{% else %}
      -e PACT_BROKER_BASE_URL
      -e PACT_BROKER_PASSWORD
      -e PACT_BROKER_USERNAME{% endif %}
      -e PROJECT_SLUG{% if cookiecutter.use_vault == "true" %}
      -e VAULT_ADDR
      -e VAULT_ID_TOKEN{% endif %}
      --entrypoint=""
      pactfoundation/pact-cli:latest-node14 ./scripts/ci_pact.sh ${PACT_CMD}

.can-i-deploy:
  extends:
    - .pact
  stage: Pact-check
  needs: ["pact-verify-test"]
  before_script:
    - >
      export PACT_CMD="can-i-deploy
      --pacticipant ${PACT_PROVIDER_NAME}
      --version ${VERSION_REF}
      --to env:${ENV_SLUG}"

can-i-deploy_development:
  extends:
    - .development
    - .can-i-deploy
  rules:
    - &skip-pact-rule
      if: $PACT_ENABLED != "true"
      when: never
    - *development-rules

can-i-deploy_staging:
  extends:
    - .staging
    - .can-i-deploy
  rules:
    - <<: *skip-pact-rule
    - *staging-rules

can-i-deploy_production:
  extends:
    - .production
    - .can-i-deploy
  rules:
    - <<: *skip-pact-rule
    - *production-rules

.build:
  stage: Build
  image: docker:20
  services:
    - docker:20-dind
  before_script:
    - export DOCKER_CONFIG=${PWD}/.dockerconfig
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:${VERSION_REF} --target remote --pull .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:${VERSION_REF}
  after_script:
    - docker logout ${CI_REGISTRY}

build_development:
  extends:
    - .development
    - .build
  needs:
    - job: can-i-deploy_development
      optional: true
    - job: test

build_staging:
  extends:
    - .staging
    - .build
  needs:
    - job: can-i-deploy_staging
      optional: true
    - job: test

build_production:
  extends:
    - .production
    - .build
  needs:
    - job: can-i-deploy_production
      optional: true
    - job: test

.deploy:
  stage: Deploy
  image:
    name: docker:20
  services:
    - docker:20-dind{% if cookiecutter.use_vault == "true" %}
  id_tokens:
    VAULT_ID_TOKEN:
      aud: ${VAULT_ADDR}{% endif %}
  variables:
    TF_ROOT: ${CI_PROJECT_DIR}/terraform/{{ cookiecutter.deployment_type }}
  before_script:
    - export TF_VAR_service_container_image=${CI_REGISTRY_IMAGE}:${VERSION_REF}
  script:
    - >
      docker run --rm
      -u `id -u`
      -v ${PWD}:${PWD}
      -w ${PWD}{% if cookiecutter.terraform_backend == "gitlab" %}
      -e CI_API_V4_URL
      -e CI_COMMIT_SHA
      -e CI_JOB_ID
      -e CI_JOB_STAGE
      -e CI_JOB_TOKEN
      -e CI_PROJECT_ID
      -e CI_PROJECT_NAME
      -e CI_PROJECT_NAMESPACE
      -e CI_PROJECT_PATH
      -e CI_PROJECT_URL{% endif %}
      -e ENV_SLUG
      -e PROJECT_DIR=${CI_PROJECT_DIR}
      -e PROJECT_SLUG
      -e STACK_SLUG
      -e TERRAFORM_BACKEND={{ cookiecutter.terraform_backend }}
      -e TERRAFORM_EXTRA_VAR_FILE=${ENV_SLUG}.tfvars
      -e TERRAFORM_VARS_DIR=${CI_PROJECT_DIR}/terraform/vars
      -e TF_ROOT{% if cookiecutter.terraform_backend == "gitlab" %}
      -e TF_STATE_NAME="env_${ENV_SLUG}"{% endif %}{% if cookiecutter.use_vault == "false" %}{% if cookiecutter.deployment_type == "digitalocean-k8s" %}
      -e TF_VAR_digitalocean_token="${DIGITALOCEAN_TOKEN}"{% endif %}
      -e TF_VAR_email_url="${EMAIL_URL}"
      -e TF_VAR_service_slug="{{ cookiecutter.service_slug }}"{% if cookiecutter.deployment_type == "other-k8s" %}
      -e TF_VAR_kubernetes_cluster_ca_certificate="${KUBERNETES_CLUSTER_CA_CERTIFICATE}"
      -e TF_VAR_kubernetes_host="${KUBERNETES_HOST}"
      -e TF_VAR_kubernetes_token="${KUBERNETES_TOKEN}"{% endif %}{% if "s3" in cookiecutter.media_storage %}
      -e TF_VAR_s3_access_id="${S3_ACCESS_ID}"
      -e TF_VAR_s3_secret_key="${S3_SECRET_KEY}"
      -e TF_VAR_s3_region="${S3_REGION}"
      -e TF_VAR_s3_host="${S3_HOST}"
      -e TF_VAR_s3_bucket_name="${S3_BUCKET_NAME}"{% endif %}
      -e TF_VAR_sentry_dsn="${SENTRY_DSN}"{% endif %}
      -e TF_VAR_service_container_image{% if cookiecutter.terraform_backend != "gitlab" %}
      -e TF_WORKSPACE="{{ cookiecutter.project_slug }}_backend_environment_${ENV_SLUG}"{% endif %}{% if cookiecutter.terraform_backend == "terraform-cloud" and cookiecutter.use_vault == "false" %}
      -e TFC_TOKEN{% endif %}{% if cookiecutter.use_vault == "true" %}
      -e VAULT_ADDR
      -e VAULT_ID_TOKEN
      -e VAULT_ROLE
      -e VAULT_SECRETS="digitalocean email k8s s3 {{ cookiecutter.service_slug }}/extra {{ cookiecutter.service_slug }}/sentry"
      -e VAULT_SECRETS_PREFIX="envs/${CI_ENVIRONMENT_NAME}"
      -e VAULT_VERSION{% endif %}
      registry.gitlab.com/gitlab-org/terraform-images/stable:latest ./scripts/deploy.sh
  artifacts:
    name: plan
    reports:
      terraform: ${TF_ROOT}/plan.json

deploy_development:
  extends:
    - .development
    - .deploy
  needs: ["build_development"]

deploy_staging:
  extends:
    - .staging
    - .deploy
  needs: ["build_staging"]

deploy_production:
  extends:
    - .production
    - .deploy
  needs: ["build_production"]

.rollback:
  extends: .deploy
  before_script:
    - export TF_VAR_service_container_image=${CI_REGISTRY_IMAGE}:${VERSION_BEFORE_REF}

rollback_development:
  extends:
    - .development
    - .rollback
  needs: ["deploy_development"]
  rules:
    - <<: *pipeline-push-rule
    - <<: *development-rule
      when: manual
      allow_failure: true

rollback_staging:
  extends:
    - .staging
    - .rollback
  needs: ["deploy_staging"]
  rules:
    - <<: *pipeline-push-rule
    - <<: *staging-rule
      when: manual
      allow_failure: true

rollback_production:
  extends:
    - .production
    - .rollback
  needs: ["deploy_production"]
  rules:
    - <<: *pipeline-push-rule
    - <<: *production-rule
      when: manual
      allow_failure: true

.create-version-tag:
  extends:
    - .pact
  stage: Pact-tag
  before_script:
    - >
      export PACT_CMD="create-version-tag
      --pacticipant ${PACT_PROVIDER_NAME}
      --version ${VERSION_REF}
      --tag env:${ENV_SLUG}"

create-version-tag_development:
  extends:
    - .create-version-tag
  needs: ["deploy_development"]
  rules:
    - <<: *skip-pact-rule
    - *development-rules

create-version-tag_staging:
  extends:
    - .create-version-tag
  needs: ["deploy_staging"]
  rules:
    - <<: *skip-pact-rule
    - *staging-rules

create-version-tag_production:
  extends:
    - .create-version-tag
  needs: ["deploy_production"]
  rules:
    - <<: *skip-pact-rule
    - *production-rules

.sentry_deploy_success:
  extends:
    - .sentry
  variables:
    SENTRY_CMD: success
  stage: Sentry
  before_script:
    - RELEASE_END=$(date +%s)

sentry_success_development:
  extends:
    - .development
    - .sentry_deploy_success
  needs: ["deploy_development"]
  rules:
    - <<: *sentry-rule
    - <<: *pipeline-push-rule
    - <<: *development-rule
      when: on_success

sentry_success_staging:
  extends:
    - .staging
    - .sentry_deploy_success
  needs: ["deploy_staging"]
  rules:
    - <<: *sentry-rule
    - <<: *pipeline-push-rule
    - <<: *staging-rule
      when: on_success

sentry_success_production:
  extends:
    - .production
    - .sentry_deploy_success
  needs: ["deploy_production"]
  rules:
    - <<: *sentry-rule
    - <<: *pipeline-push-rule
    - <<: *production-rule
      when: on_success

.sentry_deploy_failure:
  extends:
    - .sentry
  variables:
    SENTRY_CMD: failure
  stage: Sentry

sentry_failure_development:
  extends:
    - .development
    - .sentry_deploy_failure
  rules:
    - <<: *sentry-rule
    - <<: *pipeline-push-rule
    - <<: *development-rule
      when: on_failure

sentry_failure_staging:
  extends:
    - .staging
    - .sentry_deploy_failure
  rules:
    - <<: *sentry-rule
    - <<: *pipeline-push-rule
    - <<: *staging-rule
      when: on_failure

sentry_failure_production:
  extends:
    - .production
    - .sentry_deploy_failure
  rules:
    - <<: *sentry-rule
    - <<: *pipeline-push-rule
    - <<: *production-rule
      when: on_failure
