stages:
- Test
- Build
- Deploy
- Report

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - ~/.cache/pip/

test:
  stage: Test
  image: python:3.8-buster
  services:
    - postgres:12
  before_script:
    - pip install -r requirements/tests.txt
    - black --check .
    - isort --check .
    - flake8
    - mypy .
  variables:
    DATABASE_URL: "postgres://postgres:postgres@postgres:5432/{{cookiecutter.project_slug}}"
    DJANGO_CONFIGURATION: "Testing"
    DJANGO_SETTINGS_MODULE: "{{cookiecutter.project_slug}}.settings"
    POSTGRES_PASSWORD: "postgres"
  script:
    - python manage.py behave --simple
    - coverage run --concurrency=multiprocessing manage.py test --noinput --parallel --reverse
    - coverage combine
    - coverage html
    - coverage report
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 day

pages:
  stage: Report
  image: busybox
  script:
    - mv htmlcov public
  artifacts:
    paths:
      - public
  dependencies:
    - test
  only:
    - develop

build:
  stage: Build
  image: docker:20-git
  services:
    - docker:20-dind
  before_script:
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA --target prod --pull ."
    - "docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA"
  after_script:
    - "docker logout $CI_REGISTRY"
  only:
    - develop
    - master

.deploy:
  stage: Deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
    - kubectl config set-cluster my-cluster --server=${KUBE_URL} --certificate-authority="${KUBE_CA_PEM_FILE}"
    - kubectl config set-credentials admin --token=${KUBE_TOKEN}
    - kubectl config set-context my-context --cluster=my-cluster --user=admin --namespace=default
    - kubectl config use-context my-context

deploy_development:
  extends: .deploy
  only:
    - develop
  environment: development
  script:
    - sed -i "s/__IMAGE_TAG__/develop-$CI_COMMIT_SHA/" k8s/development/1_backend.yaml
    - kubectl apply -f k8s/development/

rollback_development:
  extends: .deploy
  only:
    - develop
  environment: development
  when: manual
  script:
    - sed -i "s/__IMAGE_TAG__/develop-$CI_COMMIT_BEFORE_SHA/" k8s/development/1_backend.yaml
    - kubectl apply -f k8s/development/

deploy_integration:
  extends: .deploy
  only:
    - master
  environment: integration
  script:
    - sed -i "s/__IMAGE_TAG__/master-$CI_COMMIT_SHA/" k8s/integration/1_backend.yaml
    - kubectl apply -f k8s/integration/

rollback_integration:
  extends: .deploy
  only:
    - master
  environment: integration
  when: manual
  script:
    - sed -i "s/__IMAGE_TAG__/master-$CI_COMMIT_BEFORE_SHA/" k8s/integration/1_backend.yaml
    - kubectl apply -f k8s/integration/

deploy_production:
  extends: .deploy
  only:
    - tags
  environment: production
  script:
    - sed -i "s/__IMAGE_TAG__/master-$CI_COMMIT_SHA/" k8s/production/1_backend.yaml
    - kubectl apply -f k8s/production/

rollback_production:
  extends: .deploy
  only:
    - tags
  environment: production
  when: manual
  script:
    - sed -i "s/__IMAGE_TAG__/master-$CI_COMMIT_BEFORE_SHA/" k8s/production/1_backend.yaml
    - kubectl apply -f k8s/production/
