stages:
  - Test
  - Build
  - Deploy
  - Report

variables:
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/{{cookiecutter.project_slug}}"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  POSTGRES_DB: "{{cookiecutter.project_slug}}"
  POSTGRES_INITDB_ARGS: "--no-sync"
  POSTGRES_PASSWORD: "postgres"
  VERSION_BEFORE_REF: $CI_COMMIT_BEFORE_SHA
  VERSION_REF: $CI_COMMIT_SHA

test:
  stage: Test
  image: docker:20
  services:
    - docker:20-dind
  before_script:
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker pull $CI_REGISTRY/$CI_PROJECT_PATH:test-$VERSION_BEFORE_REF || true"
    - "docker build --cache-from $CI_REGISTRY/$CI_PROJECT_PATH:test-$VERSION_BEFORE_REF -t $CI_REGISTRY/$CI_PROJECT_PATH:test-$VERSION_REF --target test --pull ."
    - "docker push $CI_REGISTRY/$CI_PROJECT_PATH:test-$VERSION_REF"
    - "docker run -e POSTGRES_DB -e POSTGRES_INITDB_ARGS -e POSTGRES_PASSWORD -d --name postgres postgres:12"
    - "docker run --name backend --link=postgres -e DATABASE_URL $CI_REGISTRY/$CI_PROJECT_PATH:test-$VERSION_REF"
    - "docker cp backend:/app/htmlcov htmlcov"
  after_script:
    - "docker logout $CI_REGISTRY"
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 day

pages:
  stage: Report
  image: busybox
  script:
    - mv htmlcov public
  artifacts:
    paths:
      - public
  dependencies:
    - test
  only:
    - develop

build:
  stage: Build
  image: docker:20
  services:
    - docker:20-dind
  before_script:
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker pull $CI_REGISTRY/$CI_PROJECT_PATH:test-$VERSION_REF || true"
    - "docker build --cache-from $CI_REGISTRY/$CI_PROJECT_PATH:test-$VERSION_REF -t $CI_REGISTRY/$CI_PROJECT_PATH:$VERSION_REF --target remote --pull ."
    - "docker push $CI_REGISTRY/$CI_PROJECT_PATH:$VERSION_REF"
  after_script:
    - "docker logout $CI_REGISTRY"
  only:
    - develop
    - master
    - tags

.deploy:
  stage: Deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
    - kubectl config set-cluster my-cluster --server=${KUBE_URL} --certificate-authority="${KUBE_CA_PEM_FILE}"
    - kubectl config set-credentials admin --token=${KUBE_TOKEN}
    - kubectl config set-context my-context --cluster=my-cluster --user=admin --namespace=default
    - kubectl config use-context my-context

deploy_development:
  extends: .deploy
  environment:
    name: development
    url: https://dev.{{cookiecutter.domain_url}}
  script:
    - sed -i "s/__IMAGE_TAG__/$VERSION_REF/" k8s/development/1_backend.yaml
    - kubectl apply -f k8s/development/
  only:
    - develop

deploy_integration:
  extends: .deploy
  environment:
    name: integration
    url: https://test.{{cookiecutter.domain_url}}
  script:
    - sed -i "s/__IMAGE_TAG__/$VERSION_REF/" k8s/integration/1_backend.yaml
    - kubectl apply -f k8s/integration/
  only:
    - master

deploy_production:
  extends: .deploy
  environment:
    name: production
    url: https://www.{{cookiecutter.domain_url}}
  script:
    - sed -i "s/__IMAGE_TAG__/$VERSION_REF/" k8s/production/1_backend.yaml
    - kubectl apply -f k8s/production/
  only:
    - tags

rollback_development:
  extends: .deploy
  environment:
    name: development
    url: https://dev.{{cookiecutter.domain_url}}
  script:
    - sed -i "s/__IMAGE_TAG__/$VERSION_BEFORE_REF/" k8s/development/1_backend.yaml
    - kubectl apply -f k8s/development/
  only:
    - develop
  when: manual

rollback_integration:
  extends: .deploy
  environment:
    name: integration
    url: https://test.{{cookiecutter.domain_url}}
  script:
    - sed -i "s/__IMAGE_TAG__/$VERSION_BEFORE_REF/" k8s/integration/1_backend.yaml
    - kubectl apply -f k8s/integration/
  only:
    - master
  when: manual

rollback_production:
  extends: .deploy
  environment:
    name: production
    url: https://www.{{cookiecutter.domain_url}}
  script:
    - sed -i "s/__IMAGE_TAG__/$VERSION_BEFORE_REF/" k8s/production/1_backend.yaml
    - kubectl apply -f k8s/production/
  only:
    - tags
  when: manual
