default_language_version:
  python: python{{ cookiecutter.python_version }}
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^(\.env_template|\.dockerignore)$
        args: ["--ignore-case", "--unique"]
      - id: fix-byte-order-marker
        args: ["--remove"]
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.29.1
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.2"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.11.1
    hooks:
      - id: pyproject-fmt
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: npx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
  - repo: https://github.com/ducminh-phan/reformat-gherkin
    rev: v3.0.1
    hooks:
      - id: reformat-gherkin
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        language: system
  - repo: https://github.com/pycqa/bandit
    rev: 1.9.3
    hooks:
      - id: bandit
        additional_dependencies: ["bandit[toml]"]
        args: ["--configfile", "pyproject.toml", "--quiet", "--recursive"]
  - repo: https://github.com/owenlamont/uv-secure
    rev: 0.15.4
    hooks:
      - id: uv-secure
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["--external-sources"]
        exclude: "(^scripts/ci_.*$|^scripts/deploy/vault.sh|^scripts/deploy/terraform.sh$)"
