default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^(\.env_template|\.dockerignore|requirements/\w*.in)$
        args: ["--ignore-case", "--unique"]
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.29.0"
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.4.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
  - repo: https://github.com/psf/black
    rev: "21.9b0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: "5.9.3"
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
        types: [json]
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear~=21.9.0
          - flake8-docstrings~=1.6.0
          - flake8-isort~=4.1.0
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910-1"
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        args: ["--exclude", ".venv,tests", "--skip", "B108"]
