version: "3.4"

services:
  {{ cookiecutter.service_slug }}:
    build:
      args:
        USER: ${USER:-appuser}
      context: .
      target: ${{ "{" }}{{ cookiecutter.service_slug|upper }}_BUILD_TARGET:-remote}
    image: ${{ "{" }}{{ cookiecutter.service_slug|upper }}_IMAGE_NAME:-{{ cookiecutter.project_slug }}_{{ cookiecutter.service_slug }}}:${{ "{" }}{{ cookiecutter.service_slug|upper }}_IMAGE_TAG:-latest}
    depends_on:
      - postgres
    environment:
      - CACHE_URL
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/{{ cookiecutter.project_slug }}}
      - DJANGO_ADMINS
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION:-Remote}
      - DJANGO_DEBUG
      - DJANGO_DEFAULT_FROM_EMAIL
      - DJANGO_SECRET_KEY
      - DJANGO_SERVER_EMAIL
      - DJANGO_SESSION_COOKIE_DOMAIN
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - EMAIL_URL{% if cookiecutter.pact_enabled %}
      - PACT_BROKER_URL
      - PACT_PROVIDER_NAME{% endif %}
      - PYTHONBREAKPOINT
      - SERVICE_PORT
    ports:
      - "${{ '{' }}{{ cookiecutter.service_slug|upper }}_PORT:-{{ cookiecutter.internal_service_port }}{{ '}' }}:${INTERNAL_SERVICE_PORT:-{{ cookiecutter.internal_service_port }}{{ '}' }}"
    user: ${USER:-appuser}

  postgres:
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_INITDB_ARGS=--no-sync
      - POSTGRES_PASSWORD=postgres
    image: postgres:14-bullseye
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
