version: "3.4"

services:

  backend:
    build:
      args:
        USER: ${USER:-appuser}
      context: .
      target: ${BACKEND_BUILD_TARGET:-remote}
    image: ${BACKEND_IMAGE_NAME:-{{ cookiecutter.project_slug }}_backend}:${BACKEND_IMAGE_TAG:-latest}
    depends_on:
      - postgres
    environment:
      - CACHE_URL
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/{{ cookiecutter.project_slug }}}
      - DJANGO_ADMINS
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_CONFIGURATION
      - DJANGO_DEBUG
      - DJANGO_DEFAULT_FROM_EMAIL
      - DJANGO_SECRET_KEY
      - DJANGO_SERVER_EMAIL
      - DJANGO_SESSION_COOKIE_DOMAIN
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - EMAIL_URL
      - PYTHONBREAKPOINT
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    user: ${USER:-appuser}

  postgres:
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_INITDB_ARGS=--no-sync
      - POSTGRES_PASSWORD=postgres
    image: postgres:13-bullseye
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
