[tool.black]
target-version = ["py310"]

[tool.coverage.html]
title = "{{cookiecutter.project_name}} - Coverage"

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing"]
data_file = ".coverages/.coverage"
disable_warnings = ["no-data-collected"]
omit = [
    ".venv/*",
    "{{cookiecutter.project_slug}}/asgi.py",
    "{{cookiecutter.project_slug}}/workers.py",
    "{{cookiecutter.project_slug}}/wsgi.py",
    "manage*.py",
    "venv/*",
]
source = ["."]

[tool.isort]
atomic = true
combine_as_imports = true
default_section = "THIRDPARTY"
known_first_party = [
    "{{cookiecutter.project_slug}}",
]
known_third_party = "django"
profile = "black"
skip = [
    ".vscode-server",
]

[tool.mypy]
ignore_missing_imports = true
python_version = "3.10"

[tool.pytest.ini_options]
DJANGO_CONFIGURATION = "Testing"
DJANGO_SETTINGS_MODULE = "{{cookiecutter.project_slug}}.settings"
