[tool.pytest.ini_options]
DJANGO_CONFIGURATION = "Testing"
DJANGO_SETTINGS_MODULE = "{{ cookiecutter.django_settings_dirname }}.settings"

[tool.coverage.html]
title = "{{cookiecutter.project_name}} - Coverage"

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing"]
data_file = ".coverages/.coverage"
disable_warnings = ["no-data-collected"]
omit = [
    ".venv/*",
    "{{cookiecutter.django_settings_dirname}}/asgi.py",
    "{{cookiecutter.django_settings_dirname}}/workers.py",
    "{{cookiecutter.django_settings_dirname}}/wsgi.py",
    "manage*.py",
    "pacts/*",
    "venv/*",
    "*/pact_states.py",
]
source = ["."]

[tool.mypy]
enable_error_code = [
    "truthy-bool",
]
ignore_missing_imports = true
python_version = "3.12"

[tool.bandit]
exclude_dirs = [
    ".venv",
    "tests",
    "features"
]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-exclude = [
    "__pycache__",
    ".pytest_cache",
    ".vscode*",
    "*/migrations/*",
]
ignore = [
    "D203",
    "D212",
    "D213",
    "D214",
    "D215",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D413",
    "D415",
    "D416",
    "D417",
]
select = [
  "A",      # flake8-builtins
  "B",      # flake8-bugbear
  "C4",     # flake8-comprehensions
  "C90",    # McCabe cyclomatic complexity
  "D",      # pydocstyle
  "DJ",     # flake8-django
  "E",      # pycodestyle errors
  "F",      # Pyflakes
  "I",      # isort
  "Q",      # flake8-quotes
  "UP",     # pyupgrade
  "W",      # pycodestyle warnings
]

[tool.ruff.per-file-ignores]
"{{ cookiecutter.django_settings_dirname }}/*sgi.py" = [
    "E402",
]
"*/migrations/*.py" = [
    "D100",
    "D101",
    "D102",
    "D104",
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.isort]
known-first-party = [
    "{{ cookiecutter.django_settings_dirname }}",
]
known-third-party = [
    "django",
]
