[tool.black]
target-version = ["py39"]

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing"]
data_file = ".coverages/.coverage"
disable_warnings = ["no-data-collected"]
omit = [
    ".venv/*",
    "*/asgi.py",
    "*/wsgi.py",
    "manage*.py",
    "venv/*",
]
source = ["."]

[tool.isort]
atomic = true
profile = "black"
combine_as_imports = true
default_section = "THIRDPARTY"
known_first_party = [
    "{{ cookiecutter.project_slug }}",
]
known_third_party = "django"
skip = [
    ".vscode-server",
]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true

[tool.pytest.ini_options]
DJANGO_CONFIGURATION = "Testing"
DJANGO_SETTINGS_MODULE = "{{ cookiecutter.project_slug }}.settings"
