apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{cookiecutter.project_slug}}-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: registry.gitlab.com/{{cookiecutter.gitlab_group_slug}}/{{cookiecutter.project_dirname}}:__IMAGE_TAG__
          ports:
            - containerPort: 8000
          env:
            # django
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_URL
            - name: DJANGO_ADMINS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_ADMINS
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_ALLOWED_HOSTS
            - name: DJANGO_CONFIGURATION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_CONFIGURATION{% if cookiecutter.use_media == "Yes" %}
            - name: DJANGO_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_ACCESS_KEY_ID
            - name: DJANGO_AWS_LOCATION
              value: "$(DJANGO_CONFIGURATION)/media"
            - name: DJANGO_AWS_S3_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_S3_HOST
            - name: DJANGO_AWS_S3_ENDPOINT_URL
              value: "https://$(DJANGO_AWS_S3_HOST)"
            - name: DJANGO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: DJANGO_AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_STORAGE_BUCKET_NAME{% endif %}
            - name: DJANGO_DEBUG
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_DEBUG
            - name: DJANGO_DEFAULT_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_DEFAULT_FROM_EMAIL
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_SECRET_KEY
            - name: DJANGO_SERVER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DJANGO_SERVER_EMAIL
            - name: EMAIL_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: EMAIL_URL
            # sentry
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              value: $(DJANGO_CONFIGURATION)
            # gunicorn
            - name: WEB_CONCURRENCY
              value: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-cluster-ip-service
  namespace: {{cookiecutter.project_slug}}-integration
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
